pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  testing:
    image: node:8.6.0
    group: testing
    commands:
      - yarn run test

  lint:
    image: node:8.6.0
    group: testing
    commands:
      - yarn run lint

  scp:
    image: appleboy/drone-scp
    host:
      - lotteryjs.com
    port: 22
    secrets: [ ssh_username, ssh_key ]
    target: /root/drone/${DRONE_REPO}
    source:
      - "*.js"
      - process.json
      - node_modules
      - Dockerfile
    when:
      branch: master
  
  ssh:
    image: appleboy/drone-ssh
    host:
      - lotteryjs.com
    port: 22
    command_timeout: 120
    secrets: [ ssh_username, ssh_key ]
    script:
      - rm -rf docker/${DRONE_REPO} && mkdir -p docker/${DRONE_REPO}
      - cp -r drone/${DRONE_REPO}/* docker/${DRONE_REPO}/
      - cd docker/${DRONE_REPO} && docker build -t boy/node . && docker rm -f app && docker run -d --name app -p 8099:8080 boy/node
    when:
      branch: master
  
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: master
